# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  increment_version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Increment version
      id: increment-version
      uses: RichardInnocent/semantic-versioning-maven@v0.0.36
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - name: increment references
      if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
      run: sed -e "s/${{ steps.increment-version.outputs.previous-version }}/${{ steps.increment-version.outputs.new-version }}/" > pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v4

  build:
    runs-on: ubuntu-latest
    needs: increment_version
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: 'temurin'
        java-version: '17'
    - run: cat /home/runner/.m2/settings.xml
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
