# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven
    - name: Build library
      env:
        SECRET_USER_NAME: ${{ github.actor }}
        SECRET_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy    
      
