# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  increment_version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.0

    - name: Increment project version
      run: mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}

    - name: increment references
      if: steps.version.outputs.previous-version != ${{ steps.version.outputs.version }}
      run: bash update-version.sh ${{ steps.version.outputs.previous-version }} ${{ steps.version.outputs.version }} 

    - name: Push tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false
        custom_tag: ${{ steps.version.outputs.version }}
        tag_prefix: ""

    - run: cat pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v4

  build:
    runs-on: ubuntu-latest
    needs: increment_version
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: 'temurin'
        java-version: '17'
    - run: cat /home/runner/.m2/settings.xml
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
