# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  increment_version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.0
      with:
        prefix: "v"

    - run: echo "VERSION=$(sed -e "s/v//g" ${{ steps.version.outputs.version }})" >> $GITHUB_ENV

    - name: Increment project version
      run: mvn versions:set -DnewVersion=$VERSION

    - name: increment references
      if: steps.version.outputs.previous-version != $VERSION
      run: bash update-version.sh ${{ steps.version.outputs.previous-version }} $VERSION

    - name: Bump version and push tag
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ env.github-token }}
        tag: $VERSION

    - run: cat pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v4

  build:
    runs-on: ubuntu-latest
    needs: increment_version
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: 'temurin'
        java-version: '17'
    - run: cat /home/runner/.m2/settings.xml
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
